// Code generated by goctl. DO NOT EDIT.
// Source: property.proto

package propertyclient

import (
	"context"

	"web/apps/property/rpc/property"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateTableReq = property.CreateTableReq
	CreateTableRsp = property.CreateTableRsp
	UpdateScoreReq = property.UpdateScoreReq
	UpdateScoreRsp = property.UpdateScoreRsp

	Property interface {
		// 更新积分
		UpdateScore(ctx context.Context, in *UpdateScoreReq, opts ...grpc.CallOption) (*UpdateScoreRsp, error)
		// 创建表
		CreateTable(ctx context.Context, in *CreateTableReq, opts ...grpc.CallOption) (*CreateTableRsp, error)
	}

	defaultProperty struct {
		cli zrpc.Client
	}
)

func NewProperty(cli zrpc.Client) Property {
	return &defaultProperty{
		cli: cli,
	}
}

// 更新积分
func (m *defaultProperty) UpdateScore(ctx context.Context, in *UpdateScoreReq, opts ...grpc.CallOption) (*UpdateScoreRsp, error) {
	client := property.NewPropertyClient(m.cli.Conn())
	return client.UpdateScore(ctx, in, opts...)
}

// 创建表
func (m *defaultProperty) CreateTable(ctx context.Context, in *CreateTableReq, opts ...grpc.CallOption) (*CreateTableRsp, error) {
	client := property.NewPropertyClient(m.cli.Conn())
	return client.CreateTable(ctx, in, opts...)
}
