// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: property.proto

package property

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PropertyClient is the client API for Property service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PropertyClient interface {
	UpdateScore(ctx context.Context, in *UpdateScoreReq, opts ...grpc.CallOption) (*UpdateScoreRsp, error)
}

type propertyClient struct {
	cc grpc.ClientConnInterface
}

func NewPropertyClient(cc grpc.ClientConnInterface) PropertyClient {
	return &propertyClient{cc}
}

func (c *propertyClient) UpdateScore(ctx context.Context, in *UpdateScoreReq, opts ...grpc.CallOption) (*UpdateScoreRsp, error) {
	out := new(UpdateScoreRsp)
	err := c.cc.Invoke(ctx, "/property.Property/UpdateScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropertyServer is the server API for Property service.
// All implementations must embed UnimplementedPropertyServer
// for forward compatibility
type PropertyServer interface {
	UpdateScore(context.Context, *UpdateScoreReq) (*UpdateScoreRsp, error)
	mustEmbedUnimplementedPropertyServer()
}

// UnimplementedPropertyServer must be embedded to have forward compatible implementations.
type UnimplementedPropertyServer struct {
}

func (UnimplementedPropertyServer) UpdateScore(context.Context, *UpdateScoreReq) (*UpdateScoreRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateScore not implemented")
}
func (UnimplementedPropertyServer) mustEmbedUnimplementedPropertyServer() {}

// UnsafePropertyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropertyServer will
// result in compilation errors.
type UnsafePropertyServer interface {
	mustEmbedUnimplementedPropertyServer()
}

func RegisterPropertyServer(s grpc.ServiceRegistrar, srv PropertyServer) {
	s.RegisterService(&Property_ServiceDesc, srv)
}

func _Property_UpdateScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateScoreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServer).UpdateScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/property.Property/UpdateScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServer).UpdateScore(ctx, req.(*UpdateScoreReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Property_ServiceDesc is the grpc.ServiceDesc for Property service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Property_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "property.Property",
	HandlerType: (*PropertyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateScore",
			Handler:    _Property_UpdateScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "property.proto",
}
