// Code generated by goctl. DO NOT EDIT.
// Source: task.proto

package server

import (
	"context"

	"web/apps/task/rpc/internal/logic"
	"web/apps/task/rpc/internal/svc"
	"web/apps/task/rpc/task"
)

type TaskServer struct {
	svcCtx *svc.ServiceContext
	task.UnimplementedTaskServer
}

func NewTaskServer(svcCtx *svc.ServiceContext) *TaskServer {
	return &TaskServer{
		svcCtx: svcCtx,
	}
}

func (s *TaskServer) UpdateProgress(ctx context.Context, in *task.UpdateProgressReq) (*task.UpdateProgressRsp, error) {
	l := logic.NewUpdateProgressLogic(ctx, s.svcCtx)
	return l.UpdateProgress(in)
}
