// Code generated by goctl. DO NOT EDIT.
// Source: task.proto

package server

import (
	"web/apps/task/rpc/internal/svc"
	"web/apps/task/rpc/task"
)

type TaskServer struct {
	svcCtx *svc.ServiceContext
	task.UnimplementedTaskServer
}

func NewTaskServer(svcCtx *svc.ServiceContext) *TaskServer {
	return &TaskServer{
		svcCtx: svcCtx,
	}
}
