// Code generated by goctl. DO NOT EDIT.
// Source: task.proto

package taskclient

import (
	"context"

	"web/apps/task/rpc/task"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UpdateProgressReq = task.UpdateProgressReq
	UpdateProgressRsp = task.UpdateProgressRsp

	Task interface {
		UpdateProgress(ctx context.Context, in *UpdateProgressReq, opts ...grpc.CallOption) (*UpdateProgressRsp, error)
	}

	defaultTask struct {
		cli zrpc.Client
	}
)

func NewTask(cli zrpc.Client) Task {
	return &defaultTask{
		cli: cli,
	}
}

func (m *defaultTask) UpdateProgress(ctx context.Context, in *UpdateProgressReq, opts ...grpc.CallOption) (*UpdateProgressRsp, error) {
	client := task.NewTaskClient(m.cli.Conn())
	return client.UpdateProgress(ctx, in, opts...)
}
