// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"web/apps/user/rpc/internal/logic"
	"web/apps/user/rpc/internal/svc"
	"web/apps/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 登录
func (s *UserServer) Login(ctx context.Context, in *user.LoginReq) (*user.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
