// Code generated by goctl. DO NOT EDIT.
// Source: property.proto

package server

import (
	"context"

	"web/apps/property/rpc/internal/logic"
	"web/apps/property/rpc/internal/svc"
	"web/apps/property/rpc/property"
)

type PropertyServer struct {
	svcCtx *svc.ServiceContext
	property.UnimplementedPropertyServer
}

func NewPropertyServer(svcCtx *svc.ServiceContext) *PropertyServer {
	return &PropertyServer{
		svcCtx: svcCtx,
	}
}

// 更新积分
func (s *PropertyServer) UpdateScore(ctx context.Context, in *property.UpdateScoreReq) (*property.UpdateScoreRsp, error) {
	l := logic.NewUpdateScoreLogic(ctx, s.svcCtx)
	return l.UpdateScore(in)
}

// 创建表
func (s *PropertyServer) CreateTable(ctx context.Context, in *property.CreateTableReq) (*property.CreateTableRsp, error) {
	l := logic.NewCreateTableLogic(ctx, s.svcCtx)
	return l.CreateTable(in)
}
