// Code generated by goctl. DO NOT EDIT.
package types

type UserInfo struct {
	Id         uint64 `json:"id"`          // 用户 ID
	Username   string `json:"username"`    // 用户名
	Password   string `json:"password"`    // 用户密码 MD5
	CreateTime int64  `json:"create_time"` // 创建时间
	UpdateTime int64  `json:"update_time"` // 更新时间
}

type LoginReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessEx"`
}
